name: Python Unit Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name if different
  pull_request:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Change this to the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust if you have specific requirements

      - name: Run unit tests
        run: python -m unittest discover -s test

