name: tests

on:
  push:
    branches:
      - main  # Change this to your main branch name if different
  pull_request:
    branches:
      - main  # Change this to your main branch name if different

jobs:

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
        target: [ x86_64, x86, aarch64, armv7, s390x, ppc64le ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover -s tests


  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
        target: [ aarch64 ]
    steps:

      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

      -   name: Update pip
          run: pip install --upgrade pip

      -   name: Install dependencies
          run: pip install -r requirements.txt

      -   name: Run unit tests
          run: python -m unittest discover -s tests

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
        target: [ x86_64, x86 ]
    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

      -   name: Install dependencies
          run: pip install -r requirements.txt

      -   name: Run unit tests
          run: python -m unittest discover -s tests
