name: tests

on:
  push:
    branches:
      - main  # Change this to your main branch name if different
  pull_request:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']  # Change this to the Python version you need

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust if you have specific requirements

      - name: Run unit tests
        run: python -m unittest discover -s tests

      - name: Run examples in examples directory
        run: |
          find examples -name "*.py" | while read -r file; do
            python "${file%/*}"
          done
